### ISSUE TITLE
No such tokenと出てしまう

### ISSUE THREAD

**Issue by kekeke29341** [payjp/payjp-ruby#18]
お世話になります。

1時間くらい詰まってるのが、
テストモードで、テスト公開鍵、秘密鍵を利用し
Pay.jpのgemを入れまして、RoRのサーバー側からpay.jpのメソッド(Payjp::Customer.createなど)を叩いてるのですが、no such tokenと言われ続けており、どうしたものかと。
また、Payjp::Plan.createは叩けて、Payjp::Charge.createはno such tokenと跳ねられます。
<img width="757" alt="スクリーンショット 2019-10-27 15 32 20" src="https://user-images.githubusercontent.com/1960224/67633610-47652e00-f8f5-11e9-9e9e-ff969745ad42.png">
<img width="663" alt="スクリーンショット 2019-10-27 15 32 11" src="https://user-images.githubusercontent.com/1960224/67633611-47fdc480-f8f5-11e9-977b-8dc2b9b9cadd.png">

**Comment by sainuio** [comment]
@kekeke29341  `Payjp::Token.create`で作成したトークンは、他のAPIで一度でも利用すると使えなくなります。
エラー該当箇所のメソッド全体を見てもいいですか？

**Comment by kekeke29341** [comment]
@sainuio ご丁寧に早速ありがとうございます！！
クライアントのページでチェックアウトでトークンを作成し、そのトークンをRoRのサーバーサイドに送り、サーバーサイドで Payjp::Customer.createをしています。
添付画像1,2とお送りします。
1: クライアントのページ
2:サーバーサイドの街灯箇所メソッド
<img width="547" alt="スクリーンショット 2019-10-27 23 28 10" src="https://user-images.githubusercontent.com/1960224/67636216-d7b16c00-f911-11e9-9d74-af2bb29c6554.png">
<img width="657" alt="スクリーンショット 2019-10-27 23 26 33" src="https://user-images.githubusercontent.com/1960224/67636219-dbdd8980-f911-11e9-8563-58cccb833af4.png">

よろしくお願いします。

**Comment by sainuio** [comment]
@kekeke29341  見せていただいたコードで特に問題が起こりそうな箇所は無いようと思えました🤔

>Payjp::Plan.createは叩けて、Payjp::Charge.createはno such tokenと跳ねられます。

この部分について少し引っかかります😲こちらは実際にどのような操作をしたのか教えていただけますか？

**Comment by kekeke29341** [comment]
@sainuio ご丁寧に夜遅くまでありがとうございます。
それは、rails console画面から
require "payjp"
Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
plan = Payjp::Plan.create( :amount => params[:amount], :interval => 'month', :currency => 'jpy')

こちらを行うと、Webブラウザから
<img width="758" alt="スクリーンショット 2019-10-28 0 15 14" src="https://user-images.githubusercontent.com/1960224/67636859-1fd38d00-f918-11e9-9948-5726a55a1d1b.png">
プランが作成されたことを確認できました。

また続いて
Payjp::Charge.create(~~~)を叩きますと、no such tokenと表示されるのですが、
同様にブラウザから「売り上げ」確認すると履歴だけは残って「支払い失敗」と表示されます。

お手数をおかけしますが、よろしくお願いします。

**Comment by sainuio** [comment]
@kekeke29341 

手元で`No such token`エラーを再現したいので、エラーがでる処理までの再現手順を完全に書いていただけると助かります😅

また、支払いのアプローチは以下の2つがあると思うのですが、両方ともコンソールから試してみて支払いができるか確認してもらえますか？

1）トークンから支払いを直接行う場合
```rb
require 'payjp'
Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

# チェックアウトからトークンを生成してもOK
card_params = { number: '4242424242424242', cvc: '123', exp_month: '1', exp_year: '2022' }
token = Payjp::Token.create({ card: card_params }, x_payjp_direct_token_generate: true)
# チェックアウトからトークンを生成してもOK

Payjp::Charge.create(amount: 2000, card: token.id, currency: 'jpy')
```

2）トークンから顧客を作成し、顧客情報から支払いを行う場合
```rb
require 'payjp'
Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

# チェックアウトからトークンを生成してもOK
card_params = { number: '4242424242424242', cvc: '123', exp_month: '1', exp_year: '2022' }
token = Payjp::Token.create({ card: card_params }, x_payjp_direct_token_generate: true)
# チェックアウトからトークンを生成してもOK

customer = Payjp::Customer.create(card: token.id) # チェックアウトから作成したトークンでもOK
Payjp::Charge.create(amount: 2000, customer: customer.id, currency: 'jpy')
```

**Comment by kekeke29341** [comment]
ご丁寧にありがとうございます！
返事が遅くなって申し訳ありません。

上記できました！ありがとうございました！
引数のx_payjp_direct_token_generate: trueが私のコードではありませんでした！

**Comment by kekeke29341** [comment]
すみません><

結局、ローカルでtokenを作って、tokenを飛ばして、サーバー側からPayjp::のメソッドを叩くと、やはり、no such tokenと言われてしまうようです。

closeしてしまいましたが、ごめんなさい、、上記のコードは、コンソール上で、実行できました

**Comment by kekeke29341** [comment]
すみません、完全に解決しました、、、

チェックアウトのところ
<script
type="text/javascript"
src="https://checkout.pay.jp/"
class="payjp-button"
data-key="ウェブサイトからコピペ"
data-on-created="onCreated"
data-submit-text="トークンを作成する"
data-partial="true">
</script>

こちらのdata-keyのところを、pay.jpのウェブサイトからコピペしたせいで、公開鍵がそのまんまになってしました。大変ご迷惑をおかけしました、、解決しました、、、
すみません、ありがとうございました！
