### ISSUE TITLE
支払い情報を取得時のエラーレスポンスが取得できない

### ISSUE THREAD

**Issue by yuki0627** [payjp/payjp-ruby#5]
エラーレスポンスが取得できません
異常値をAPIを呼びエラーを発生させた際エラーレスポンスが来ず、例外(Payjp::InvalidRequestError)が発生します
期待する結果はエラーが発生した際はエラーレスポンスが取得できることです

試した処理
支払情報を取得

正常(支払情報がある)
`@res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716b')`
結果
{ "id": "ch_9ac9e317a18a3afa8f3534853716b", "amount": 3500, "amount_refunded": 0, "captured": true, "captured_at": 1458960766, "card": {"id":"car_7949ddf458fa8886aaa1d549fbf6","address_city":null,"address_line1":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":"unchecked","brand":"Visa","country":null,"created":1458960766,"customer":"cus_a67723dc15826b6a9be34bf6f0a0","cvc_check":"passed","exp_month":12,"exp_year":2017,"fingerprint":"e1d8225886e3a7211127df751c86787f","last4":"4242","livemode":false,"metadata":{},"name":"HOGE HOGE","object":"card"}, "created": 1458960766, "currency": "jpy", "customer": "cus_a67723dc15826b6a9be34bf6f0a0", "description": null, "expired_at": null, "failure_code": null, "failure_message": null, "livemode": false, "metadata": {}, "object": "charge", "paid": true, "refund_reason": null, "refunded": false, "subscription": null }

異常(支払情報がない)
`@res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716a')`
結果(例外)
Payjp::InvalidRequestError: There is no charge with ID: ch_9ac9e317a18a3afa8f3534853716a
from /usr/local/rvm/gems/ruby-2.2.1/gems/payjp-0.0.3/lib/payjp.rb:224:in `handle_api_error'

期待する結果(下記のリファレンス通りエラーレスポンスで戻ってくるです)
https://pay.jp/docs/api/#支払いを情報を取得
{
"error": {
"message": "There is no charge with ID: ch_9ac9e317a18a3afa8f3534853716a",
"param": "id",
"status": 404,
"type": "client_error"
}
}

やってないこと
他の処理でのエラーレスポンスの発生検証

**Comment by keketa** [comment]
ご報告ありがとうございます。
ライブラリとしてはリクエストエラー時に例外 `Payjp::InvalidRequestError` が発生するのは正しい挙動になります。
[支払い情報を取得](https://pay.jp/docs/api/#%E6%94%AF%E6%89%95%E3%81%84%E3%82%92%E6%83%85%E5%A0%B1%E3%82%92%E5%8F%96%E5%BE%97) などの現状のリファレンスのサンプルコードでは、curlリクエストにおけるJSONレスポンスが記載されており、各言語のライブラリごとのレスポンスの記載になっていません。
混乱を招いてしまい申し訳ございませんが、こちらはすぐにライブラリごとの正しいレスポンスを記載するよう修正を進めます。

ちなみにエラー時にJSONレスポンスを出力する場合、下記のようなコードで出力可能です:

```
begin
  @res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716a')
rescue Payjp::InvalidRequestError => e
  body = e.json_body
  puts body
end
```	

出力:
```
{:error=>{:message=>"There is no charge with ID: ch_9ac9e317a18a3afa8f3534853716a", :param=>"id", :status=>404, :type=>"client_error"}}
```

詳しくはAPIリファレンスの[エラーハンドリング](https://pay.jp/docs/api/?ruby#エラーハンドリング)をご確認ください。
