### ISSUE TITLE
Can't install payjp

### ISSUE THREAD

**Issue by cometheart314** [payjp/payjp-ruby#7]
payjpのライブラリをインストールしようとして、
>gem install payjp 
を実行すると以下のエラーメッセージでインストールできません。

$ gem install payjp
ERROR:  Could not find a valid gem 'payjp' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://api.rubygems.org/specs.4.8.gz)

どうしたら解決できるでしょうか？

こちらの ruby のバージョンは
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Mac OS X 10.10.4

よろしくお願いします。

**Comment by pay-kun** [comment]
ご報告ありがとうございます。
エラー内容はネットワークに起因する `gem install` 時の一般的なトラブルだと思われます。

原因の例:
- DNSの問題で "rubygem.org" の名前解決ができていない 
- SSL通信がファイアウォールなどで許可されていない

再度お試しいただくか、ネットワーク環境を確認をお願いします。

**Comment by cometheart314** [comment]
お騒がせしました。解決しました。
原因は、Proxyを経由していないのに、.bash_profile に Proxyを指定する以下のような行があったためでした。
export http_proxy=http://xxxx.xxxxxx.co.jp:10080
上記の行をコメントアウトしたら正常に動作しました。

**Comment by pay-kun** [comment]
承知しました! 返信、ありがとうございます。
